Update Privacy.vue
Fixed a bug where the web app wouldn't build since the Vue component wasn't initialized.

```
error TS1208: 'Privacy.vue.ts' cannot be compiled under '--isolatedModules' because it is considered a global script file. Add an import, export, or an empty 'export {}' statement to make it a module.
error TS2306: File '/app/web/src/pages/Privacy.vue.ts' is not a module.
```